SUDO: required
servies:
  - docker


before_install:
  - docker build -t cbalbuena/docker-react -f dockerfile.dev . 

script:
  - docker run -e CI=true cbalbuena/docker-react npm run test -- --coverage

language: generic
